### PR TITLE
Changed Text background for mobile view

### PR DESCRIPTION
**Pull request by TeraSurror**
Issue: #34 

Changes:

1. Added background to Text in mobile view.
2. Added transition animation to nav links.

### CODE REVIEW

**Comment by KushalBhanot** [comment]
Hey, @TeraSurror!

I value your contributions. But test your work again. It's not responsive in mobile view. A white opacity doesn't look good. Try to make it a shade of black. And the transitions in the nav links are fine. Also, try to adjust the padding-top for this section to make everything move a bit upwards.

Fix it. And I'll merge the changes.

**Comment by TeraSurror** [comment]
Sure. Will do that!

**Comment by KushalBhanot** [comment]
There's some whitespace between the hero and the following section. Fix that and I'll merge the changes. Nice work!

**Comment by TeraSurror** [comment]
Hey @KushalBhanot 

I have removed the whitespace.

**Comment by KushalBhanot** [comment]
Nice work, @TeraSurror 🤟🏻⚡️

**Pull request merged**
